# Generated by Django 4.2.7 on 2023-12-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewswaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapclaim',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled')], default='Pending'),
        ),
    ]
