# Generated by Django 4.2.7 on 2023-12-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewswaps', '0002_alter_swapclaim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapclaim',
            name='swap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='brewswaps.brewswap'),
        ),
    ]
